# Generated by Django 6.0.4 on 2026-05-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('job_seeker', 'job_seeker'), ('company_admin', 'company_admin')], max_length=20),
        ),
    ]
